services:
  # Frontend (Agora na porta 3008)
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: marketplacefront
    ports:
      - 3008:3008
    environment:
      - NODE_ENV=production
    networks:
      - boraimpactar
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: marketplaceback
    ports:
      - 3018:3018
    environment:
      DB_SCHEMA: produtos_sociais
      DB_DIALECT: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: bi_banco
      DB_USER: docker
      DB_PASS: docker
    networks:
      - boraimpactar

networks:
  boraimpactar:
    external: true
