version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres.gqdwkbmxgulupqlptzor
      POSTGRES_PASSWORD: Y2YcQiQd07uDNXBN
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: marketplace_backend
    depends_on:
      - database
    environment:
      DB_HOST: aws-0-sa-east-1.pooler.supabase.com
      DB_PORT: 5432
      DB_USER: postgres.gqdwkbmxgulupqlptzor
      DB_PASS: Y2YcQiQd07uDNXBN
      DB_NAME: postgres
    ports:
      - "3018:3018"

volumes:
  postgres_data:
