version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: bi_banco
    volumes:
      - pgdata:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d bi_banco"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - boraimpactar

volumes:
  pgdata:

networks:
  boraimpactar:
    external: true
